# Generated by Django 4.2.5 on 2024-05-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountExpires', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('displayName', models.CharField(max_length=20)),
                ('lastLogon', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=100)),
                ('manager', models.CharField(max_length=20)),
                ('pwdLastSet', models.CharField(max_length=20)),
                ('sAMAccountName', models.CharField(max_length=20)),
            ],
        ),
    ]
